version: "2.3"
services:

  postgres:
    image: postgres:13.1
    mem_limit: 200M
    container_name: pg_greetgo_conf_jdbc
    restart: always
    ports:
      - "25432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "111"

  mariadb:
    image: mariadb:10.5.8
    mem_limit: 200M
    container_name: mariadb_greetgo_conf_jdbc
    restart: always
    ports:
      - "23306:3306"
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "111"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    mem_limit: 200M
    restart: always
    volumes:
      - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper/log:/var/lib/zookeeper/log"
    ports:
      - "51078:2181"
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: "2181"

#  zookeeper:
#    image: zookeeper:3.6.2
#    user: "0:0"
#    mem_limit: 200M
#    restart: always
#    ports:
#      - "51078:2181"
#    volumes:
#      - "./volumes/zookeeper/data:/data"
#      - "./volumes/zookeeper/log:/datalog"
#    environment:
#      ZOO_MY_ID: 1

  zoonavigator:
    image: elkozmon/zoonavigator:1.1.0
    mem_limit: 200M
    restart: always
    ports:
      - "51079:9000"       # http://localhost:51079
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_ID: "MAIN"
      CONNECTION_MAIN_NAME: "main"
      CONNECTION_MAIN_CONN: "zookeeper:2181"
